---
title: "Naver relation dashboard"
runtime : shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: yeti
---

```{r global_packages}
# library(devtools)
# devtools::install_github("lovetoken/rdevteam")
# https://github.com/lovetoken/rdevteam
# https://lovetoken.gitbooks.io/r-dev-team-open-seminar/content/b3c4-c804-acfc-c81c/b124-c774-bc84-c5f0-ad00-ac80-c0c9-c5b4-cd94-cd9c-c800-c7a5-d504-b85c-adf8-b7a8-b9cc-b4e4-ae30/ad00-b828-ae30-c220-bcc4-b9ac-c11c-ce58.html
library(rdevteam)
library(shiny)
library(flexdashboard)
library(dplyr)
library(DT)
library(networkD3)
library(bsplus)
```
Sidebar {.sidebar}
=================================================

```{r sidebar_ui}
textInput("ui1", "Keyword", "현대모비스")
actionButton("act", "Change apply")

d <- reactive({
  keyword <- input$ui1
  naverRelation(keyword, depth=2)
})
```

Summary
=================================================

### Plot

```{r}
renderForceNetwork({
  req(input$act)
  isolate({
    d() %>% plot
  })
})
```

### Rawdata

```{r}
renderDT({
  req(input$act)
  isolate({
    d() %>% datatable
  })
})
```

About
=================================================

본 대쉬보드는 네이버 연관검색어 서비스를 기반으로 합니다.
사용된 도구는 R, Shiny package, flexdashboard packages 등이 이용됩니다.
