---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

# File Upload {.sidebar}

```{r, echo = FALSE}
fileInput("file1", "Choose CSV File",
                multiple = TRUE,
                accept = c("text/csv",
                         "text/comma-separated-values,text/plain",
                         ".csv"))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
######################################
## Download file with the same name ##
######################################
downloadHandler(
    filename = paste("NEW", input$file$name),
    content = function(file) {
        write.csv(x = read.csv(input$file$datapath),
                   file = file, row.names = FALSE)
    },
    outputArgs = list(label = "Download Uploaded File"))

```

### Chart C

```{r}

```
